export type language = 'zh-CN' | 'en-US';
export interface ISetting {
  locale: language;
  authProvider: string;
  logo: 'Visual Builder';
  version: 'fluent';
  theme: 'default';
  isSidebarOpen: Boolean;
  isSupportChatOpen: Boolean;
  isMobileView: Boolean;
  isMobileMenuOpen: Boolean;
  isMenuCollapsed: Boolean;
  isPreselectedOpen: Boolean;
  preselectedVariant: 'default';
  menuLayoutType: 'left';
  routerAnimation: 'slide-fadein-up';
  menuColor: 'gray';
  authPagesColor: 'gray';
  isAuthTopbar: true;
  primaryColor: '#4b7cf3';
  leftMenuWidth: 256;
  isMenuUnfixed: Boolean;
  isMenuShadow: Boolean;
  isTopbarFixed: Boolean;
  isTopbarSeparated: Boolean;
  isGrayTopbar: Boolean;
  isContentMaxWidth: Boolean;
  isAppMaxWidth: Boolean;
  isGrayBackground: Boolean;
  isCardShadow: true;
  isSquaredBorders: Boolean;
  isBorderless: Boolean;
  layoutMenu: 'classic';
  layoutTopbar: 'v1';
  layoutBreadcrumbs: 'v1';
  layoutFooter: 'v1';
  flyoutMenuType: 'flyout';
  flyoutMenuColor: 'blue';
}
