export type language = 'zh-CN' | 'en-US';
export interface ISetting {
  locale: language;
  logo: string;
  authProvider: 'jwt';
  version: 'fluent';
  theme: 'default' | 'dark';
  isSidebarOpen: Boolean;
  isSupportChatOpen: Boolean;
  isMobileView: Boolean;
  isTabletView: Boolean;
  isMobileMenuOpen: Boolean;
  isMenuCollapsed: Boolean;
  isPreselectedOpen: Boolean;
  preselectedVariant: 'default';
  menuLayoutType: 'left';
  routerAnimation: 'slide-fadein-up';
  menuColor: 'gray';
  authPagesColor: 'gray';
  isAuthTopbar: true;
  primaryColor: string;
  leftMenuWidth: number;
  isMenuUnfixed: Boolean;
  isMenuShadow: Boolean;
  isTopbarFixed: Boolean;
  isTopbarSeparated: Boolean;
  isGrayTopbar: Boolean;
  isContentMaxWidth: Boolean;
  isAppMaxWidth: Boolean;
  isGrayBackground: Boolean;
  isCardShadow: true;
  isSquaredBorders: Boolean;
  isBorderless: Boolean;
  layoutMenu: 'classic';
  layoutTopbar: 'v1';
  layoutBreadcrumbs: 'v1';
  layoutFooter: 'v1';
  flyoutMenuType: 'flyout';
  flyoutMenuColor: 'blue';
  isSettingsOpen: Boolean;
}
